[build]
  # The directory to change to before starting a build
  base = "."
  
  # Directory to publish (relative to root of your repo)
  publish = "."
  
  # Default build command
  command = ""

[[redirects]]
  # Handle client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Set any environment variables here
  NODE_VERSION = "18"
