[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && gunicorn app:app"
healthcheckPath = "/health"
healthcheckTimeout = 100

[deploy.restartPolicy]
type = "on_failure"
maxRetries = 10
